# Default configuration for both sides of the nickey keyboard

# I2C global enablement for external modules
CONFIG_I2C=y

# LPPS Driver enablement
CONFIG_LPPS=y

# ZMK Standard Mouse/Pointing functional enablement
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
